[build]
command = "npm install --legacy-peer-deps && npm install -D @tailwindcss/postcss postcss-import tailwindcss postcss autoprefixer --legacy-peer-deps && npm run build"
publish = ".next"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"
NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
package = "@netlify/plugin-nextjs"
